#!/bin/sh
#
# JMXEval execution script
#
# Syntax: check_jmxeval <config-xml-file> [<options>]
#
# If JAVA_HOME environment variable is not set, uncomment the following
# line and set the value as the path to root of the Java directory 
#
# JAVA_HOME=/path/to/jdk-1.5.0
#
# Executes JMXEval
#
BASE_DIR=`dirname $0`
LIB_DIR="$BASE_DIR/lib"

# build classpath from main jar and all jars in lib
CP=$BASE_DIR/jmxeval-1.2.6.jar
for i in "$LIB_DIR/*.jar"; do
  CP="$CP:$i";
done

$JAVA_HOME/bin/java -classpath "$CP" com.adahas.tools.jmxeval.App $@
